using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TIPOS_DE_VARÍAVEIS
{
    class Calculadora
    {
        public void somar()

        {
            int num1 = 5;
            int num2 = 6;
            int resultado = num1 + num2;
            Console.WriteLine("o resultado é: {0} ", resultado.ToString());
        }
    }
}
